### ISSUE TITLE
Flexible environment setup for part-time swift usage

### ISSUE THREAD

**Issue by cmcfarlen** [swift-server/swiftly#110]
Swiftly is great for managing swift releases.  The problem I run into that keeps me from using swiftly over swiftenv is that much of the time I need other, non-swift clang/clang++ versions to be on my path for C++ development.  With swiftenv I have a script like this that I can source:

```
echo "Activating swift..."

export SWIFTENV_ROOT="$HOME/.swiftenv"
export PATH="$SWIFTENV_ROOT/bin:$PATH"
eval "$(swiftenv init -)"
```

`swiftenv init -` evals something like:

```
export PATH="${HOME}/.swiftenv/shims:${PATH}"
command swiftenv rehash 2>/dev/null
source ${HOME}/.swiftenv/libexec/../libexec/../completions/swiftenv.bash
```

This lets me activate swift when I need it but otherwise keeps my compiler setup as normal and other shells I start are not affected.  This is very convenient, but have not been able to figure out something similar for swiftly.

Any advice for similar behavior from swiftly?

Thanks!

**Comment by kkebo** [comment]
How about using this script instead of your swiftenv script?

```shell
echo "Activating swift..."

. $HOME/.local/share/swiftly/env.sh
```

**Comment by cmcfarlen** [comment]
Ooh, Idk how I missed this.  Thanks!  Perhaps this wasn't available when I last tried swiftly.

Thanks!
