### ISSUE TITLE
No instructions for installing Swiftly itself

### ISSUE THREAD

**Issue by MahdiBM** [swift-server/swiftly#37]
There should be some instructions about how to install Swiftly itself.
A command like this will work as a quick-start:
```
curl -L https://raw.githubusercontent.com/swift-server/swiftly/main/install/swiftly-install.sh | bash
```

**Comment by adam-fowler** [comment]
This should probably be the first section of the README.

**Comment by MahdiBM** [comment]
Does that mean I need to edit the PR? or was this before you notice the PR?

**Comment by adam-fowler** [comment]
> Does that mean I need to edit the PR? or was this before you notice the PR?

Before I saw the PR
