### ISSUE TITLE
Allow installation on derived and unsupported platforms

### ISSUE THREAD

**Issue by patrickfreed** [swift-server/swiftly#60]
To enable users to use swiftly on platforms that aren't explicitly supported by Swift, we could provide the option during swiftly installation to use the toolchains intended for another supported platform. 

e.g. If installing on debian, a user could select Ubuntu 20.04 as the platform they'd like their toolchains to download from, and it's likely they would work ok (I haven't tried this though).

**Comment by makoni** [comment]
Another case - Ubuntu 23.04. I can't install Swift using swiftly, had to do a manual installation of Swift for 22.04 :)

**Comment by Diggory** [comment]
Yes please. Anything that makes it easy to install and update Swift on Raspberry Pi OS would be very gratefully received.

**Comment by adam-fowler** [comment]
I think this can be split into two tasks. 

1) The user explicitly indicates the platform they want to install via a command line parameter 
2) reading the ID_LIKE variable from os-release file.

**Comment by patrickfreed** [comment]
I think we may also want to introduce a CLI option for the platform too, which will skip the entire platform detection process. This will help when installing swiftly as part of a CI task, for example.

I'll try to get a PR up for this tonight.

**Comment by patrickfreed** [comment]
This has been implemented and deployed!
