### ISSUE TITLE
Error: `getopt` must be installed

### ISSUE THREAD

**Issue by filip-sakel** [swift-server/swiftly#73]
I got this error when trying to install swiftly on MacOS 13.5 beta (22G5038d). I'm using zsh as my default shell.

```bash
> curl -L https://swift-server.github.io/swiftly/swiftly-install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18846  100 18846    0     0   308k      0 --:--:-- --:--:-- --:--:--  347k
 --
Error: getopt must be installed from the util-linux package to run swiftly-install
```

**Comment by patrickfreed** [comment]
For the time being, swiftly is only supported on Linux, so installing on macOS won't work.

For anyone else who might have this issue on Linux: this specific error message seen here can appear on certain Linux distributions (I think Amazon Linux 2 doesn't come with `util-linux` actually), but can be resolved by installing the `util-linux` package from your distro's package manager. See [here](https://github.com/swift-server/swiftly/pull/63#discussion_r1334404282) for justification for adding the dependency.
