### ISSUE TITLE
Prompt to remove existing Swift installation 

### ISSUE THREAD

**Issue by MahdiBM** [swift-server/swiftly#85]
* Updated to 5.9.1 via Swiftly, `swift --version` would still show `5.8.1`.
* Tried `which swift` which said: `/usr/bin/swift`.
* I had noticed Swiftly says its installation is at `/root/.local/bin/swift` instead.
* Manually deleted `/usr/bin/swift`.
* Added `/root/.local/bin/` to PATH.
  * Not sure if this not-existing there wasn't my fault
  * For more context I overrided the older installation of Swiftly with a new one, not sure if it matters.
* `swift --version` now correctly shows `5.9.1`.

This process could be handled by Swiftly itself.
There could be a prompt to ask user to remove their existing Swift installation if it's in a non-Swiftly directory.

**Comment by adam-fowler** [comment]
That sounds particularly dangerous asking Swiftly to remove a directory it doesn't manage.

**Comment by patrickfreed** [comment]
I agree that removing the installation is probably not safe for us to do as part of swiftly's installation, but adding a warning that a different installation has precedence sounds like a decent idea to me.

Regarding adding it to your path, swiftly creates an `env.sh` in swiftly's home directory (which is by default `$HOME/.local/share/swiftly`) which updates your PATH correctly, and by default swiftly adds a line to source this file to your `.profile`. Next time you log in (or do `bash -login`) it should be picked up automatically, or you can just source it in your current shell.

swiftly-install.sh is also _supposed_ to print a message instructing you to source that file in your current shell if `$HOME/.local/bin` isn't already on your PATH, but it looks like if you have an existing installation of Swift elsewhere, this message isn't printed properly. We should definitely fix that.

**Comment by carlynorama** [comment]
Had the same problem, but I just restarted the shell.  Offer up a temp fix of suggesting a manual path update in that same message that says to run env.sh

https://github.com/swift-server/swiftly/pull/93

**Comment by patrickfreed** [comment]
Just pushed a commit (https://github.com/swift-server/swiftly/commit/76a23583dc177b369f9be54ab6f338bef37c77be) to print a warning when an existing installation has been detected:
```
swiftly has been succesfully installed!

Once you log in again, swiftly should be accessible from your PATH.
To begin using swiftly from your current shell, first run the following command:

    . $HOME/.local/share/swiftly/env.sh

Then to install the latest version of Swift, run 'swiftly install latest'

Warning: existing installation of Swift detected at /usr/bin/swift
To ensure swiftly-installed toolchains can be found by the shell, uninstall any existing Swift installation(s).
To ensure the current shell can find swiftly-installed toolchains, you may also need to run 'hash -r'.
```
As a side note, this also made me realize "successfully" has been mispelled all this time ( :facepalm: ), so I also also fixed that.

>swiftly-install.sh is also supposed to print a message instructing you to source that file in your current shell if $HOME/.local/bin isn't already on your PATH, but it looks like if you have an existing installation of Swift elsewhere, this message isn't printed properly. We should definitely fix that.

This part of my comment isn't entirely accurate--swiftly-install.sh is supposed to print this message if it can't find `swiftly` (not `swift`) or if a non-default `SWIFTLY_HOME` was specified, and it properly does this.

Going to close this out, please feel free to re-open if more needs to be done to address this fully. Thanks for filing this issue!
