### ISSUE TITLE
Amazon Linux 2023 - There isn't enough space

### ISSUE THREAD

**Issue by kicsipixel** [swift-server/swiftly#96]
I am trying to run `swiftly install latest` on t3..micro AWS EC2 instance but  I got the error:

```
Fetching the latest stable Swift release...
Installing Swift 5.10.0
                                                                                   Downloading Swift 5.10.0
77% [=====================================================================================================================================----------------------------------------]
Downloaded 451.7 MiB of 579.1 MiB
Error: The operation could not be completed. There isn’t enough space.
```

I run `df -T` command:

```
Filesystem       Type     1K-blocks    Used Available Use% Mounted on
devtmpfs         devtmpfs      4096       0      4096   0% /dev
tmpfs            tmpfs       463368       0    463368   0% /dev/shm
tmpfs            tmpfs       185348     444    184904   1% /run
/dev/nvme0n1p1   xfs        8310764 1635088   6675676  20% /
tmpfs            tmpfs       463372       0    463372   0% /tmp
/dev/nvme0n1p128 vfat         10202    1310      8892  13% /boot/efi
tmpfs            tmpfs        92672       0     92672   0% /run/user/1000
```

```
[ec2-user@ip-172-31-40-159 ~]$ swiftly --version
0.2.0
```

```
$ uname -a
Linux ip-172-31-40-159.eu-north-1.compute.internal 6.1.79-99.164.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Feb 27 18:02:23 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

The same configuration, with Ubuntu,  works fine. What do I miss?

**Comment by adam-fowler** [comment]
Swift isn't supported on Amazon Linux 2023 at this point in time. There is ongoing work to get it working. 

There is a long thread on the forums about getting it working. See https://forums.swift.org/t/recommended-way-to-develop-for-amazon-linux-2023/69958/36. 

Also once it is working Swiftly will probably need to be updated to support it.

**Comment by kkk669** [comment]
I think the reason is your `/tmp` is too small. Your `/tmp` looks like 452 MiB and the download failed at 451.7 MiB.

`swiftly install` downloads a toolchain to `/tmp` temporarily.

https://github.com/swift-server/swiftly/blob/22ba150d6ea4323b4c7f6f1d04f0eeba4de5004e/Sources/Swiftly/Install.swift#L143

**Comment by kicsipixel** [comment]
Yes, the `/tmp` was the primary issue. Secondary is what Adam linked. Thank you.
